---
galaxy_info:
  author: Azraf Al Monzim
  min_ansible_version: "2.0"
  description: Installs Git on Linux using apt or on macOS using homebrew
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

    - name: macOS
      versions:
        - all
  role_name: my_git_role
