# roles/git/tasks/main.yml
- include_tasks: ../check_os_family.yml

- name: Set node version
  set_fact:
    nodejs_version: "20.5.1"

- name: Mac OS X | Install Node.js and npm on macOS using homebrew
  block:
    - name: Install Node.js and npm on macOS
      when: "'Darwin' in os_result.stdout"
      homebrew:
        name: node
        state: present

- name: Mac OS | Intall npm
  block:
    - name: Intall npm
      when: "'Darwin' in os_result.stdout"
      homebrew:
        name: npm
        state: present

# roles/node/tasks/main.yml

- name: Linux | Install Node.js and npm on Debian using apt
  block:
    - name: Install Node.js and npm on Debian
      when: "'Linux' in os_result.stdout"
      apt:
        name: nodejs
        state: present

- name: Linux | Install npm on Debian using apt
  block:
    - name: Install npm on Debian
      when: "'Linux' in os_result.stdout"
      apt:
        name: npm
        state: present
